# -*- coding: utf-8 -*-
"""Colorimétrie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEKYEASmMxmkU1hNdBxrEFUcI4qarQwA
"""

import streamlit as st

# Dictionnaire : code couleur → (adjectif1, adjectif2, adjectif3)
color_database = {
    "#8B0000": ("chaud", "foncé", "dense"),
    "#FF4500": ("foncé", "chaud", "dense"),
    "#CD5C5C": ("dense", "chaud", "foncé"),
    "#FFD700": ("chaud", "clair", "doux"),
    "#E0FFFF": ("froid", "clair", "léger")
}

st.title("🎨 Outil de Colorimétrie")

st.markdown("Entrez les **trois adjectifs** qui qualifient la personne, **dans l’ordre exact**.")

adj1 = st.text_input("Premier adjectif").strip().lower()
adj2 = st.text_input("Deuxième adjectif").strip().lower()
adj3 = st.text_input("Troisième adjectif").strip().lower()

if adj1 and adj2 and adj3:
    profil = (adj1, adj2, adj3)
    resultats = [code for code, attribs in color_database.items() if attribs == profil]

    if resultats:
        st.success("Couleurs correspondantes :")
        for code in resultats:
            st.color_picker(label=code, value=code, key=code)
    else:
        st.warning("❌ Aucune couleur trouvée pour cette combinaison exacte.")